#!/bin/bash -xe
set -uxe
set -o pipefail
VERSION=`git describe --tags --always`

mydir=$(dirname $0)
git fetch origin
cd "$mydir/../.."

make docker-package
aws s3 cp --acl public-read --recursive bin/${VERSION} s3://observeinc/terraform-provider-observe/${VERSION}
