

input IncidentQueryInput @goModel(model: "observe/meta/metatypes.IncidentQueryInput") {
    text: String!
}

extend type Query {
    getIncidentsForUser(u: UserId!): [Incident!]!
    getIncidentsForWorksheet(w: ObjectId!): [Incident!]!
    getIncidentsForDashboard(d: ObjectId!): [Incident!]!
    getIncidentsForStatus(s: IncidentStatus!, startingAt: Time, endingAt: Time): [Incident!]!
    getIncidentsForTextQuery(s: IncidentQueryInput!): [Incident!]!
}

extend type Mutation {
    addIncidentUsers(i: ObjectId!, us: [UserId!]!): Incident!
    removeIncidentUsers(i: ObjectId!, us: [UserId!]!): Incident!
    addIncidentWorksheets(i: ObjectId!, ws: [ObjectId!]!): Incident!
    removeIncidentWorksheets(i: ObjectId!, ws: [ObjectId!]!): Incident!
    addIncidentDashboards(i: ObjectId!, ds: [ObjectId!]!): Incident!
    removeIncidentDashboards(i: ObjectId!, ds: [ObjectId!]!): Incident!
}
