name: terraform

on:
  pull_request:
    paths:
      - infrastructure/**

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: terraform fmt
        run: terraform fmt -check -recursive
      - name: terraform init
        run: terraform init -backend=false
      - name: terraform validate
        run: terraform validate -no-color

