name: terraform

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform.yml'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
